CREATE TABLE `dream`.`dream_channel` (
  `CODE` INT NOT NULL COMMENT '编码',
  `P_CODE` INT NULL COMMENT '父编码',
  `NAME` VARCHAR(80) NULL COMMENT '名称',
  PRIMARY KEY (`CODE`))
COMMENT = '栏目';


CREATE TABLE `dream`.`dream_article` (
  `ID` INT NOT NULL COMMENT '主键',
  `TITLE` VARCHAR(200) NULL COMMENT '标题',
  `CONTENT` TEXT NULL COMMENT '内容',
  `CHAN_ID` INT NULL COMMENT '栏目ID',
  `ATIME` VARCHAR(20) NULL COMMENT '添加时间',
  PRIMARY KEY (`ID`))
COMMENT = '文章';


CREATE TABLE `dream`.`dream_task` (
  `ID` INT NOT NULL,
  `TITLE` VARCHAR(200) NULL COMMENT '标题',
  `DESCP` VARCHAR(400) NULL COMMENT '说明',
  `TTYPE` DECIMAL(1) NULL COMMENT '类型 (未完成/已完成)',
  `START` VARCHAR(20) NULL COMMENT '开始时间',
  `ENDTIME` VARCHAR(20) NULL COMMENT '结束时间',
  PRIMARY KEY (`ID`))
COMMENT = '任务';

ALTER TABLE `dream`.`dream_task` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `dream`.`dream_channel` 
CHANGE COLUMN `CODE` `CODE` INT(11) NOT NULL AUTO_INCREMENT COMMENT '编码' ;

ALTER TABLE `dream`.`dream_article` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键' ;

