CREATE TABLE `dream`.`dream_channel` (
  `CODE` INT NOT NULL COMMENT '编码',
  `P_CODE` INT NULL COMMENT '父编码',
  `NAME` VARCHAR(80) NULL COMMENT '名称',
  PRIMARY KEY (`CODE`))
COMMENT = '栏目';


CREATE TABLE `dream`.`dream_article` (
  `ID` INT NOT NULL COMMENT '主键',
  `TITLE` VARCHAR(200) NULL COMMENT '标题',
  `CONTENT` TEXT NULL COMMENT '内容',
  `CHAN_ID` INT NULL COMMENT '栏目ID',
  `ATIME` VARCHAR(20) NULL COMMENT '添加时间',
  PRIMARY KEY (`ID`))
COMMENT = '文章';


CREATE TABLE `dream`.`dream_task` (
  `ID` INT NOT NULL,
  `TITLE` VARCHAR(200) NULL COMMENT '标题',
  `DESCP` VARCHAR(400) NULL COMMENT '说明',
  `TTYPE` DECIMAL(1) NULL COMMENT '类型 (未完成/已完成)',
  `START` VARCHAR(20) NULL COMMENT '开始时间',
  `ENDTIME` VARCHAR(20) NULL COMMENT '结束时间',
  PRIMARY KEY (`ID`))
COMMENT = '任务';

ALTER TABLE `dream`.`dream_task` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `dream`.`dream_channel` 
CHANGE COLUMN `CODE` `CODE` INT(11) NOT NULL AUTO_INCREMENT COMMENT '编码' ;

ALTER TABLE `dream`.`dream_article` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键' ;

ALTER TABLE `dream`.`dream_article` 
ADD COLUMN `SUMMARY` VARCHAR(300) NULL COMMENT '摘要' AFTER `ATIME`,
ADD COLUMN `LOCALURL` VARCHAR(100) NULL COMMENT '本地HTML路径' AFTER `SUMMERY`;


CREATE TABLE `dream`.`dream_file` (
  `ID` VARCHAR(40) NOT NULL COMMENT '主键',
  `NAME` VARCHAR(200) NULL COMMENT '文件名',
  `DISNAME` VARCHAR(200) NULL COMMENT '显示名',
  `MTYPE` VARCHAR(40) NULL COMMENT '类型',
  `FSIZE` VARCHAR(45) NULL COMMENT '大小',
  `PATH` VARCHAR(100) NULL COMMENT '路径',
  `DATAID` VARCHAR(40) NULL,
  `ATIME` VARCHAR(23) NULL COMMENT '添加时间',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC));

  
CREATE TABLE `dream`.`dream_config` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CONFKEY` VARCHAR(45) NULL COMMENT 'KEY',
  `CONFVALUE` VARCHAR(400) NULL COMMENT '配置值',
  PRIMARY KEY (`ID`))
COMMENT = '配置表';  

ALTER TABLE `dream`.`dream_article` 
ADD COLUMN `IMGIDS` VARCHAR(400) NULL AFTER `LOCALURL`;



CREATE TABLE `dream`.`dream_act_log` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `model_type` VARCHAR(45) NULL COMMENT '所属模块',
  `act_type` VARCHAR(10) NULL COMMENT '操作类型',
  `dataid` VARCHAR(45) NULL COMMENT '数据主键',
  `atime` VARCHAR(23) NULL COMMENT '操作时间',
  PRIMARY KEY (`ID`))
COMMENT = '操作记录';



ALTER TABLE `dream`.`dream_article` 
ADD COLUMN `SORTNUM` INT NULL COMMENT '排序' AFTER `IMGIDS`;

ALTER TABLE `dream`.`dream_article` 
CHANGE COLUMN `CHAN_ID` `CHANID` INT(11) NULL DEFAULT NULL COMMENT '栏目ID' ;

ALTER TABLE `dream`.`dream_article` 
ADD COLUMN `CHANNAME` VARCHAR(45) NULL COMMENT '栏目' AFTER `SORTNUM`;

INSERT INTO `dream`.`dream_config` (`ID`, `CONFKEY`, `CONFVALUE`) VALUES ('11', 'INDEX_URL', 'http://localhost:8080/solr/collection1');


CREATE TABLE `dream`.`dream_sicker` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `NAME` VARCHAR(45) NULL COMMENT '姓名',
  `AGE` INT NULL COMMENT '年龄',
  `JIGUAN` VARCHAR(45) NULL COMMENT '籍贯',
  `INTIME` VARCHAR(23) NULL COMMENT '入院时间',
  `OUTTIME` VARCHAR(23) NULL COMMENT '出院时间',
  `KESHI` VARCHAR(45) NULL COMMENT '科室',
  `BEDNUM` VARCHAR(45) NULL COMMENT '床位号',
  `INNUM` VARCHAR(45) NULL COMMENT '入院号',
  `SICKDESC` TEXT NULL COMMENT '说明',
  `MEMO` VARCHAR(2000) NULL COMMENT '备注',
  PRIMARY KEY (`ID`));
  
  
  
CREATE TABLE `dream`.`dream_dict` (
  `CODE` VARCHAR(45) NOT NULL COMMENT '主键',
  `NAME` VARCHAR(45) NULL COMMENT '名称',
  PRIMARY KEY (`CODE`))
ENGINE = InnoDB
COMMENT = '字典';

CREATE TABLE `dream`.`dream_dict_entry` (
  `CODE` VARCHAR(45) NOT NULL COMMENT '编号',
  `PCODE` VARCHAR(45) NULL COMMENT '父编号',
  `NAME` VARCHAR(45) NULL COMMENT '名称',
  `ESORT` VARCHAR(45) NULL COMMENT '排序',
  `DICTID` VARCHAR(45) NULL COMMENT '字典编码'
COMMENT = '字典项';


ALTER TABLE `dream`.`dream_dict_entry` 
ADD COLUMN `ID` INT NOT NULL AUTO_INCREMENT FIRST,
ADD PRIMARY KEY (`ID`);


ALTER TABLE `dream`.`dream_dict_entry` 
CHANGE COLUMN `ESORT` `ESORT` INT NULL DEFAULT NULL COMMENT '排序' ;


ALTER TABLE `dream`.`dream_dict_entry` 
ADD COLUMN `DLEVEL` INT NULL COMMENT '层级' AFTER `DICTID`;


CREATE TABLE `dream`.`dream_menu` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(45) NULL COMMENT '名称',
  `url` VARCHAR(45) NULL COMMENT '地址',
  `mtype` VARCHAR(10) NULL COMMENT '类型',
  `mclass` VARCHAR(100) NULL COMMENT '样式',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '菜单';

ALTER TABLE `dream`.`dream_menu` 
ADD COLUMN `msort` INT NULL COMMENT '排序' AFTER `mclass`;


ALTER TABLE `dream`.`dream_menu` 
ADD COLUMN `pid` INT NULL COMMENT '父ID' AFTER `msort`;


ALTER TABLE `dream`.`dream_menu` 
ADD COLUMN `mlevel` INT NULL COMMENT '层级' AFTER `pid`,
ADD COLUMN `mpath` VARCHAR(100) NULL COMMENT '路径' AFTER `mlevel`;



CREATE TABLE `dream`.`tb_dept` (
  `code` VARCHAR(45) NOT NULL COMMENT '编码',
  `pcode` VARCHAR(45) NULL COMMENT '父编码',
  `name` VARCHAR(50) NULL COMMENT '名称',
  `dlevel` INT NULL COMMENT '层级',
  `dpath` VARCHAR(200) NULL COMMENT '路径',
  `dsort` INT NULL COMMENT '排序',
  PRIMARY KEY (`code`))
COMMENT = '部门';


ALTER TABLE `dream`.`tb_user` 
ADD COLUMN `deptcode` VARCHAR(45) NULL COMMENT '部门' AFTER `sex`,
ADD COLUMN `usort` INT NULL COMMENT '排序' AFTER `deptcode`;

ALTER TABLE `dream`.`tb_user` 
CHANGE COLUMN `id` `id` VARCHAR(45) NOT NULL COMMENT '主键' ;

ALTER TABLE `dream`.`tb_user` 
ADD COLUMN `loginname` VARCHAR(45) NULL COMMENT '登录名' AFTER `id`;


