CREATE TABLE `dream`.`dream_channel` (
  `CODE` INT NOT NULL COMMENT '编码',
  `P_CODE` INT NULL COMMENT '父编码',
  `NAME` VARCHAR(80) NULL COMMENT '名称',
  PRIMARY KEY (`CODE`))
COMMENT = '栏目';


CREATE TABLE `dream`.`dream_article` (
  `ID` INT NOT NULL COMMENT '主键',
  `TITLE` VARCHAR(200) NULL COMMENT '标题',
  `CONTENT` TEXT NULL COMMENT '内容',
  `CHAN_ID` INT NULL COMMENT '栏目ID',
  `ATIME` VARCHAR(20) NULL COMMENT '添加时间',
  PRIMARY KEY (`ID`))
COMMENT = '文章';


CREATE TABLE `dream`.`dream_task` (
  `ID` INT NOT NULL,
  `TITLE` VARCHAR(200) NULL COMMENT '标题',
  `DESCP` VARCHAR(400) NULL COMMENT '说明',
  `TTYPE` DECIMAL(1) NULL COMMENT '类型 (未完成/已完成)',
  `START` VARCHAR(20) NULL COMMENT '开始时间',
  `ENDTIME` VARCHAR(20) NULL COMMENT '结束时间',
  PRIMARY KEY (`ID`))
COMMENT = '任务';

ALTER TABLE `dream`.`dream_task` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `dream`.`dream_channel` 
CHANGE COLUMN `CODE` `CODE` INT(11) NOT NULL AUTO_INCREMENT COMMENT '编码' ;

ALTER TABLE `dream`.`dream_article` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键' ;

ALTER TABLE `dream`.`dream_article` 
ADD COLUMN `SUMMARY` VARCHAR(300) NULL COMMENT '摘要' AFTER `ATIME`,
ADD COLUMN `LOCALURL` VARCHAR(100) NULL COMMENT '本地HTML路径' AFTER `SUMMERY`;


CREATE TABLE `dream`.`dream_file` (
  `ID` VARCHAR(40) NOT NULL COMMENT '主键',
  `NAME` VARCHAR(200) NULL COMMENT '文件名',
  `DISNAME` VARCHAR(200) NULL COMMENT '显示名',
  `MTYPE` VARCHAR(40) NULL COMMENT '类型',
  `FSIZE` VARCHAR(45) NULL COMMENT '大小',
  `PATH` VARCHAR(100) NULL COMMENT '路径',
  `DATAID` VARCHAR(40) NULL,
  `ATIME` VARCHAR(23) NULL COMMENT '添加时间',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC));

  
CREATE TABLE `dream`.`dream_config` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CONFKEY` VARCHAR(45) NULL COMMENT 'KEY',
  `CONFVALUE` VARCHAR(400) NULL COMMENT '配置值',
  PRIMARY KEY (`ID`))
COMMENT = '配置表';  

ALTER TABLE `dream`.`dream_article` 
ADD COLUMN `IMGIDS` VARCHAR(400) NULL AFTER `LOCALURL`;



CREATE TABLE `dream`.`dream_act_log` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `model_type` VARCHAR(45) NULL COMMENT '所属模块',
  `act_type` VARCHAR(10) NULL COMMENT '操作类型',
  `dataid` VARCHAR(45) NULL COMMENT '数据主键',
  `atime` VARCHAR(23) NULL COMMENT '操作时间',
  PRIMARY KEY (`ID`))
COMMENT = '操作记录';

